spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mapsa
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
